/*  SCE CONFIDENTIAL
 *  PlayStation(R)3 Programmer Tool Runtime Library 475.001
 *  Copyright (C) 2008 Sony Computer Entertainment Inc.
 *  All Rights Reserved.
 */
 
void main
(
	float4 position	: POSITION,
	float3 texcoord	: TEXCOORD0,
	float4 color	: COLOR,

	out float4 oPosition : POSITION,
	out float3 oTexCoord : TEXCOORD0,
	out float4 oColor    : COLOR
)
{
	oPosition = position;
	oTexCoord = texcoord;
	oColor = color;
}
